import {
  AddTextIcon,
  UploadIcon,
  ChangeFontIcon,
  BackgroundIcon,
  DeleteIcon,
} from "@/assets";

export const events = [
  {
    id: 1,
    label: "Birthday",
    value: "Birthday",
  },
  {
    id: 2,
    label: "Wedding",
    value: "Wedding",
  },
  {
    id: 3,
    label: "Graduation",
    value: "Graduation",
  },
  {
    id: 4,
    label: "Hangout",
    value: "Hangout",
  },
  {
    id: 5,
    label: "Houseparty",
    value: "House party",
  },
];

export const images = [
  {
    id: 1,
    filterName: "Elegant Birthday Bash",
    info: "Celebrate your special day with style and elegance using this stunning template.",
    src: "/canvas/birthday1.png",
    source: "/template/birthday1.png",
    type: "BIRTHDAY",
    alt: "Elegant Birthday Bash Template",
  },
  {
    id: 2,
    filterName: "Fun Birthday Party",
    info: "Throw a fun and memorable birthday party with this lively template.",
    src: "/canvas/birthday2.png",
    source: "/template/birthday2.png",
    type: "BIRTHDAY",
    alt: "Fun Birthday Party Template",
  },
  {
    id: 3,
    filterName: "Chic Birthday Celebration",
    info: "Host a chic and sophisticated birthday celebration with this stylish template.",
    src: "/canvas/birthday3.png",
    source: "/template/birthday3.png",
    type: "BIRTHDAY",
    alt: "Chic Birthday Celebration Template",
  },
  {
    id: 4,
    filterName: "Romantic Wedding Invite",
    info: "Invite your guests to a romantic wedding with this elegant and classy template.",
    src: "/canvas/wedding1.png",
    source: "/template/wedding1.png",
    type: "WEDDING",
    alt: "Romantic Wedding Invite Template",
  },
  {
    id: 5,
    filterName: "Elegant Wedding Announcement",
    info: "Announce your wedding in a sophisticated and elegant way with this beautiful template.",
    src: "/canvas/wedding2.png",
    source: "/template/wedding2.png",
    type: "WEDDING",
    alt: "Elegant Wedding Announcement Template",
  },
  {
    id: 6,
    filterName: "Stylish Wedding Card",
    info: "Send stylish and beautiful wedding cards using this elegant template.",
    src: "/canvas/wedding3.png",
    source: "/template/wedding3.png",
    type: "WEDDING",
    alt: "Stylish Wedding Card Template",
  },
  {
    id: 7,
    filterName: "Professional Business Flyer",
    info: "Promote your business professionally with this sleek and modern flyer template.",
    src: "/canvas/cooperate1.png",
    source: "/template/cooperate1.png",
    type: "COOPERATE",
    alt: "Professional Business Flyer Template",
  },
  {
    id: 8,
    filterName: "Corporate Event Flyer",
    info: "Advertise your corporate events effectively with this sophisticated flyer template.",
    src: "/canvas/cooperate2.png",
    source: "/template/cooperate2.png",
    type: "COOPERATE",
    alt: "Corporate Event Flyer Template",
  },
  {
    id: 9,
    filterName: "Business Meeting Flyer",
    info: "Organize your business meetings with this professional and clean flyer template.",
    src: "/canvas/cooperate3.png",
    source: "/template/cooperate3.png",
    type: "COOPERATE",
    alt: "Business Meeting Flyer Template",
  },
  {
    id: 10,
    filterName: "Casual Hangout Invite",
    info: "Invite your friends to a casual hangout with this fun and laid-back template.",
    src: "/canvas/hangout1.png",
    source: "/template/hangout1.png",
    type: "HANGOUT",
    alt: "Casual Hangout Invite Template",
  },
  {
    id: 11,
    filterName: "Weekend Hangout Flyer",
    info: "Plan a weekend hangout with friends using this vibrant and exciting flyer template.",
    src: "/canvas/hangout2.png",
    source: "/template/hangout2.png",
    type: "HANGOUT",
    alt: "Weekend Hangout Flyer Template",
  },
  {
    id: 12,
    filterName: "Hangout Party Invite",
    info: "Invite your friends to a hangout party with this cool and stylish template.",
    src: "/canvas/hangout3.png",
    source: "/template/hangout3.png",
    type: "HANGOUT",
    alt: "Hangout Party Invite Template",
  },
  {
    id: 13,
    filterName: "Miscellaneous Event Flyer",
    info: "Advertise various events with this versatile and attractive flyer template.",
    src: "/canvas/others1.png",
    source: "/template/others1.png",
    type: "OTHERS",
    alt: "Miscellaneous Event Flyer Template",
  },
  {
    id: 14,
    filterName: "General Event Flyer",
    info: "Promote general events with this clean and simple flyer template.",
    src: "/canvas/others2.png",
    source: "/template/others2.png",
    type: "OTHERS",
    alt: "General Event Flyer Template",
  },
  {
    id: 15,
    filterName: "All-Purpose Event Flyer",
    info: "Use this versatile template for any event you plan to organize.",
    src: "/canvas/others3.png",
    source: "/template/others3.png",
    type: "OTHERS",
    alt: "All-Purpose Event Flyer Template",
  },
];

export const editActions = [
  {
    id: 1,
    label: "Add Text",
    icon: <AddTextIcon />,
  },
  {
    id: 2,
    label: "Upload Image",
    icon: <UploadIcon />,
  },
  {
    id: 3,
    label: "Uplaod Element",
    icon: <UploadIcon />,
  },
  {
    id: 4,
    label: "Change font",
    icon: <ChangeFontIcon />,
  },
  {
    id: 5,
    label: "BG color",
    icon: <BackgroundIcon />,
  },
  {
    id: 6,
    label: "Delete",
    icon: <DeleteIcon />,
  },
];

export const popularFonts = [
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Courier New",
  "Verdana",
  "Georgia",
  "Palatino",
  "Garamond",
  "Bookman",
  "Comic Sans MS",
  "Blenda Script",
  "Roboto 3D",
  "Lobster 3D",
  "Zilap 3D",
  "HYPERWAVE 3D",
];
