import {
  AddTextIcon,
  UploadIcon,
  ChangeFontIcon,
  BackgroundIcon,
  DeleteIcon,
} from "@/assets";

export const events = [
  {
    id: 1,
    label: "Birthday",
    value: "Birthday",
  },
  {
    id: 2,
    label: "Wedding",
    value: "Wedding",
  },
  {
    id: 3,
    label: "Graduation",
    value: "Graduation",
  },
  {
    id: 4,
    label: "Hangout",
    value: "Hangout",
  },
  {
    id: 5,
    label: "Houseparty",
    value: "House party",
  },
];

export const images = [
  {
    id: 1,
    filterName: "Elegant Birthday Bash",
    info: "Celebrate your special day with style and elegance using this stunning template.",
    src: "/canvas/birthday1.png",
    source: "/template/birthday1.png",
    type: "BIRTHDAY",
    alt: "Elegant Birthday Bash Template",
  },
  {
    id: 2,
    filterName: "Fun Birthday Party",
    info: "Throw a fun and memorable birthday party with this lively template.",
    src: "/canvas/birthday2.png",
    source: "/template/birthday2.png",
    type: "BIRTHDAY",
    alt: "Fun Birthday Party Template",
  },
  {
    id: 3,
    filterName: "Chic Birthday Celebration",
    info: "Host a chic and sophisticated birthday celebration with this stylish template.",
    src: "/canvas/birthday3.png",
    source: "/template/birthday3.png",
    type: "BIRTHDAY",
    alt: "Chic Birthday Celebration Template",
  },
  {
    id: 4,
    filterName: "Romantic Wedding Invite",
    info: "Invite your guests to a romantic wedding with this elegant and classy template.",
    src: "/canvas/wedding1.png",
    source: "/template/wedding1.png",
    type: "WEDDING",
    alt: "Romantic Wedding Invite Template",
  },
  {
    id: 5,
    filterName: "Elegant Wedding Announcement",
    info: "Announce your wedding in a sophisticated and elegant way with this beautiful template.",
    src: "/canvas/wedding2.png",
    source: "/template/wedding2.png",
    type: "WEDDING",
    alt: "Elegant Wedding Announcement Template",
  },
  {
    id: 6,
    filterName: "Stylish Wedding Card",
    info: "Send stylish and beautiful wedding cards using this elegant template.",
    src: "/canvas/wedding3.png",
    source: "/template/wedding3.png",
    type: "WEDDING",
    alt: "Stylish Wedding Card Template",
  },
  {
    id: 7,
    filterName: "Professional Business Flyer",
    info: "Promote your business professionally with this sleek and modern flyer template.",
    src: "/canvas/cooperate1.png",
    source: "/template/cooperate1.png",
    type: "COOPERATE",
    alt: "Professional Business Flyer Template",
  },
  {
    id: 8,
    filterName: "Corporate Event Flyer",
    info: "Advertise your corporate events effectively with this sophisticated flyer template.",
    src: "/canvas/cooperate2.png",
    source: "/template/cooperate2.png",
    type: "COOPERATE",
    alt: "Corporate Event Flyer Template",
  },
  {
    id: 9,
    filterName: "Business Meeting Flyer",
    info: "Organize your business meetings with this professional and clean flyer template.",
    src: "/canvas/cooperate3.png",
    source: "/template/cooperate3.png",
    type: "COOPERATE",
    alt: "Business Meeting Flyer Template",
  },
  {
    id: 10,
    filterName: "Casual Hangout Invite",
    info: "Invite your friends to a casual hangout with this fun and laid-back template.",
    src: "/canvas/hangout1.png",
    source: "/template/hangout1.png",
    type: "HANGOUT",
    alt: "Casual Hangout Invite Template",
  },
  {
    id: 11,
    filterName: "Weekend Hangout Flyer",
    info: "Plan a weekend hangout with friends using this vibrant and exciting flyer template.",
    src: "/canvas/hangout2.png",
    source: "/template/hangout2.png",
    type: "HANGOUT",
    alt: "Weekend Hangout Flyer Template",
  },
  {
    id: 12,
    filterName: "Hangout Party Invite",
    info: "Invite your friends to a hangout party with this cool and stylish template.",
    src: "/canvas/hangout3.png",
    source: "/template/hangout3.png",
    type: "HANGOUT",
    alt: "Hangout Party Invite Template",
  },
  {
    id: 13,
    filterName: "Miscellaneous Event Flyer",
    info: "Advertise various events with this versatile and attractive flyer template.",
    src: "/canvas/others1.png",
    source: "/template/others1.png",
    type: "OTHERS",
    alt: "Miscellaneous Event Flyer Template",
  },
  {
    id: 14,
    filterName: "General Event Flyer",
    info: "Promote general events with this clean and simple flyer template.",
    src: "/canvas/others2.png",
    source: "/template/others2.png",
    type: "OTHERS",
    alt: "General Event Flyer Template",
  },
  {
    id: 15,
    filterName: "All-Purpose Event Flyer",
    info: "Use this versatile template for any event you plan to organize.",
    src: "/canvas/new2.png",
    source: "/canvas/new2.png",
    type: "OTHERS",
    alt: "All-Purpose Event Flyer Template",
  },
];
export const items = [
  {
    id: 1,
    src: "/items/numbers/1.png",
    alt: "item",
  },
  {
    id: 2,
    src: "/items/numbers/2.png",
    alt: "item",
  },
  {
    id: 3,
    src: "/items/numbers/3.png",
    alt: "item",
  },
  {
    id: 4,
    src: "/items/numbers/4.png",
    alt: "item",
  },
  {
    id: 5,
    src: "/items/numbers/5.png",
    alt: "item",
  },
  {
    id: 6,
    src: "/items/numbers/6.png",
    alt: "item",
  },
  {
    id: 7,
    src: "/items/numbers/7.png",
    alt: "item",
  },
  {
    id: 8,
    src: "/items/numbers/8.png",
    alt: "item",
  },
  {
    id: 9,
    src: "/items/numbers/9.png",
    alt: "item",
  },
  {
    id: 10,
    src: "/items/numbers/10.png",
    alt: "item",
  },
  {
    id: 11,
    src: "/items/numbers/11.png",
    alt: "item",
  },
  {
    id: 12,
    src: "/items/numbers/12.png",
    alt: "item",
  },
  {
    id: 13,
    src: "/items/numbers/13.png",
    alt: "item",
  },
  {
    id: 14,
    src: "/items/numbers/14.png",
    alt: "item",
  },
  {
    id: 15,
    src: "/items/numbers/15.png",
    alt: "item",
  },
  {
    id: 16,
    src: "/items/numbers/16.png",
    alt: "item",
  },
  {
    id: 17,
    src: "/items/numbers/17.png",
    alt: "item",
  },
  {
    id: 18,
    src: "/items/numbers/18.png",
    alt: "item",
  },
  {
    id: 19,
    src: "/items/numbers/19.png",
    alt: "item",
  },
  {
    id: 20,
    src: "/items/icons/1.png",
    alt: "item",
  },
  {
    id: 21,
    src: "/items/icons/2.png",
    alt: "item",
  },
  {
    id: 22,
    src: "/items/icons/3.png",
    alt: "item",
  },
  {
    id: 23,
    src: "/items/icons/4.png",
    alt: "item",
  },
  {
    id: 24,
    src: "/items/icons/5.png",
    alt: "item",
  },
  {
    id: 25,
    src: "/items/icons/6.png",
    alt: "item",
  },
  {
    id: 26,
    src: "/items/icons/7.png",
    alt: "item",
  },
  {
    id: 27,
    src: "/items/icons/8.png",
    alt: "item",
  },
  {
    id: 28,
    src: "/items/icons/9.png",
    alt: "item",
  },
  {
    id: 29,
    src: "/items/vignette/1.png",
    alt: "item",
  },
  {
    id: 30,
    src: "/items/vignette/2.png",
    alt: "item",
  },
  {
    id: 31,
    src: "/items/vignette/3.png",
    alt: "item",
  },
  {
    id: 32,
    src: "/items/vignette/4.png",
    alt: "item",
  },
  {
    id: 33,
    src: "/items/vignette/5.png",
    alt: "item",
  },
  {
    id: 34,
    src: "/items/vignette/6.png",
    alt: "item",
  },
  {
    id: 35,
    src: "/items/vignette/7.png",
    alt: "item",
  },
  {
    id: 36,
    src: "/items/vignette/8.png",
    alt: "item",
  },
  {
    id: 37,
    src: "/items/vignette/9.png",
    alt: "item",
  },
];

export const editActions = [
  {
    id: 1,
    label: "Add Text",
    icon: <AddTextIcon />,
  },
  {
    id: 2,
    label: "Upload Image",
    icon: <UploadIcon />,
  },
  {
    id: 3,
    label: "Add Element",
    icon: <UploadIcon />,
  },
  {
    id: 4,
    label: "Change Font",
    icon: <ChangeFontIcon />,
  },
  {
    id: 5,
    label: "BG Color",
    icon: <BackgroundIcon />,
  },
  {
    id: 6,
    label: "Delete",
    icon: <DeleteIcon />,
  },
];

export const popularFonts = [
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Courier New",
  "Verdana",
  "Georgia",
  "Palatino",
  "Garamond",
  "Bookman",
  "Comic Sans MS",
  "Blenda Script",
  "Roboto",
  "Lobster",
  "Hyperwave",
  "Autobiograph",
  "Autumn in November",
  "Bernadette",
  "Bier Signature",
  "Boston Brush",
  "Brush Script",
  "Black Witches",
  "Edwardian Script",
  "Elephant",
  "Freestyle Script",
  "Gabriela Smhasa",
  "Katoria Script Regular",
  "Kaufmann BT",
  "Lust Script",
  "Rage Italic",
  "Rogertt",
  "SCRIPT MT Bold",
  "Agon Regul",
  "Basketville Old Face",
  "Bodoni Bd BT",
  "Bronzier Medium",
  "Century",
  "Cinzel Decorative",
  "Copperplate Gothic Bold",
  "Didot",
  "Engravers MT",
  "Gloucester MT Extra Condensed",
  "Goudy Stout",
  "Jagerlay Bold Italic",
  "Kage-Freebies Black",
  "Vaimek Regular",
  "Wide Latin",
  "Antonio",
  "Space Grotesk Semi Bold",
  "Bebas Neue",
  "Dala Moa",
  "Eras Bold",
  "Tenon X-Bold Italic",
  "Franklin Gothic Heavy",
  "Futura Hv BT",
  "Gilroy-ExtraBoldItalic",
  "Gotham-UltraItalic",
  "Helvetica Bold",
  "Impact",
  "Nordams",
  "Product Sans Black",
  "Steelfish Bold Italic",
  "Tinkoff Sans Medium",
];
